### ISSUE TITLE
Can’t do a port check above 60000 on your website

### ISSUE THREAD

**Issue by DogeIII** [dsgnr/portchecker.io#216]
Hello, 

when you try to do a port check of a port above 60000 it will say "Provide a port between 1 and 65535"
![IMG_1348](https://github.com/user-attachments/assets/f4904899-120f-4c60-a20a-ae0cf6f4b2e8)

**Comment by dsgnr** [comment]
Hey @DogeIII, thank you for raising this! I've rolled out a regex change to the front-end form validation.
