### ISSUE TITLE
[Feature Suggestion] Reply to HTTP GET

### ISSUE THREAD

**Issue by yurividal** [dsgnr/portchecker.io#232]
Hi.
I would like to suggest a feature, which would allow users to query an open port by executing a curl command.
The idea is that if someone executes `curl portchecker.io/443` the server would respond with a simple true or false string if port 443 is reachable. . This would allow for a quick query to check if a port-forwarding is working.

I had this idea after using `curl ipinfo.io/ip` to find my public IP.

**Comment by yurividal** [comment]
This would also require the API to accept an empty value for "host", and replace it with the IP of the endpoint that is requesting the call

**Comment by yurividal** [comment]
To anyone trying to accomplish this, i managed to get this to work by  putting a container of portchecker.io behing my existing nginx, with the following locations:

````
    location / {
        proxy_pass http://10.10.10.5:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # API proxy
    location /api/ {
        proxy_pass http://10.10.10.5:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ /(\d+\.\d+\.\d+\.\d+)/(\d+) {
        # Capture the IP and port from the URL
        set $ip $1;
        set $port $2;
        rewrite ^ /api/v1/query break;
        proxy_set_header Content-Type application/json;
        proxy_set_body '{"host":"$ip","ports":["$port"]}';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_method POST;
        proxy_pass http://10.10.10.5:8000;
    }


 location ~ /(\d+) {

        set $port $1;
        set $ip $remote_addr;
        rewrite ^ /api/v1/query break;
        proxy_set_header Content-Type application/json;
        proxy_set_body '{"host":"$ip","ports":["$port"]}';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_method POST;
        proxy_pass http://10.10.10.5:8000;

        }
````

10.10.10.5 is the IP of the host running the docker containers. 
8081 is the frontend port mapped to the frontend container 8081:80

If someone does `curl portchecker.<.mydomain>/<port>` it will automatically find the public IP of the device requesting the informtion, and check if port <port> is open.

It also works with the format `curl portchecker.<.mydomain>/< publicIP >/< port >

**Comment by dsgnr** [comment]
Hey, thank you for your suggestion!

Whilst I'm not totally against this idea in principle, production does not make use of `X-Real-IP` to maintain user privacy and so there's no real way of obtaining the client address. As a side note, the idea of using Nginx to compile a request body feels bad so I'd definitely prefer to avoid that approach. Due to the lack of `X-Real-IP`, the UI reaches out to CloudFlares trace functionality, which maintains the privacy first approach of this app by the clients browser auto populating the address search field. 

The only real alternative I can think of is to create a new `GET` API route which will respond to something like `api.portchecker.io/<ip/hostname>/<port>` and return a boolean value.

Welcome your thoughts on this!

**Comment by yurividal** [comment]
I get your concern, and indeed, implementing it on the backend, instead of in nginx is a safer approach.
Regarding the privacy concern, maybe have a disclaimer informing that if used this way, the server must identify the user IP, but won't store it. As a network engineer (and definetly NOT a developer), I am usually most focussed on quicky checking if a service I configured is reachable, and having my public IP known to a server is not a big deal. doing curl domain.tld/port is so much quicker than opening a browser, going to canyouseeme.org, typing my public ip and port. 

This is what my customized page looks like:
![image](https://github.com/user-attachments/assets/6110e128-d1f9-4556-949d-fbab3e96fc85)


Maybe a disclaimer above the first command would sufice.

But, its totally up to you. As i said, i have a workarround that works for me, and i totally understand if you don't want to implement it. I will probably be the only one using my version anyways.
