### ISSUE TITLE
3.1.1 doesn't allow for customized index.html

### ISSUE THREAD

**Issue by yurividal** [dsgnr/portchecker.io#265]
Hi. 

I'm trying to monut a customized version of the index.html to my container.
````
    volumes:
      - ./frontend/web/src/index.html:/usr/share/nginx/html/index.html
````

It used to work until v3.1.1
Now, when i try to mount it, the container fails to start:
````
sed: can't move '/usr/share/nginx/html/index.htmlFBioCE' to '/usr/share/nginx/html/index.html': Resource busy
````

**Comment by dsgnr** [comment]
Hey @yurividal,

Thank you for reporting this. I have just merged and released a fix for this.
