### ISSUE TITLE
Building docker image on Linux

### ISSUE THREAD

**Issue by ZEROF** [dsgnr/portchecker.io#5]
Hi,

First of all thank you for resolving previous issue, but as I'm almost 100% sure that you are using macOS, you can't have same Docker image build issue as Linux users.

To bypass issue, I needed to add this block of code to your package.json

```
    "optionalDependencies": {
        "fsevents": "*"
    }
```
After that build work well. Sorry for not sending pull request, but I'm not sure if you can test this on your side too.

P.S. Not, related, but I want to have default port set to 443, how I can manage this without breaking value variable.

![image](https://user-images.githubusercontent.com/2687905/145426644-ce410774-2c78-4f6f-9ef5-5ba950322fc1.png)

Best regards

**Comment by dsgnr** [comment]
Hey @ZEROF, thank you for raising this issue.

There are long-standing complaints about this message throughout the community in npm/yarn. I am planning on upgrading Yarn to v3 with the addition of utilising the yarnrc to hide specific messages. However, this is an `info` message, and so there isn't actually anything wrong here (this is part of the complaints upstream). I will be able to look into changing the package dependency system next week.

I have also raised an issue for your feature request in https://github.com/dsgnr/portchecker.io/issues/6

**Comment by ZEROF** [comment]
Hello,

I'm going to test your solution for port. But don't forget to add this:

    "optionalDependencies": {
        "fsevents": "*"
    }

Because even it's info message, build don't work on Linux.

Build crash here:

![image](https://user-images.githubusercontent.com/2687905/145598812-7c63f19b-e02f-4339-b49c-0671a9d16e60.png)

When I add this to to package.json, everything is working.

![image](https://user-images.githubusercontent.com/2687905/145598992-6ccb5f16-0d07-4957-977f-ff8a2f1814da.png)
![image](https://user-images.githubusercontent.com/2687905/145599146-be447afd-395d-4a7a-9e75-d32daa527a60.png)

**Comment by dsgnr** [comment]
Are you able to provide some more information about the OS version you're running, and perhaps your Docker version? I'm unable to replicate that on my test device:

~~~
root@index:~/portchecker.io/webui# cat /etc/issue
Ubuntu 18.04.6 LTS \n \l
root@index:~/portchecker.io/webui# docker -v
Docker version 20.10.11, build dea9396
root@index:~/portchecker.io/webui# docker build . --no-cache
Sending build context to Docker daemon  411.1kB
Step 1/11 : FROM node:alpine AS builder
 ---> bb1fcdaff936
Step 2/11 : COPY package.json yarn.lock ./
 ---> c39bd7f01b8c
Step 3/11 : RUN yarn install && yarn global add webpack
 ---> Running in 2d2e9c88b456
yarn install v1.22.15
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
Done in 24.16s.
yarn global v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "webpack@5.65.0" with binaries:
      - webpack
Done in 5.39s.
Removing intermediate container 2d2e9c88b456
 ---> c7f444d00385
Step 4/11 : COPY . ./app
~~~

**Comment by ZEROF** [comment]
Hi,

I can confirm you, now everything is OK. I removed previous repository from my laptop, did new git clone, and after that build did work. I think it was related for node alpine image I had previously on my PC, after cleaning all earlier builds related to this project, and removing node image all went well.

I have custom Linux, but it's based on Ubuntu 20.04 with docker 20.10.11.
