### ISSUE TITLE
Feature Request: Allow default port to be defined in environment

### ISSUE THREAD

**Issue by dsgnr** [dsgnr/portchecker.io#6]
This issue relates to a feature request in https://github.com/dsgnr/portchecker.io/issues/5 to allow the default port to be changed.

My proposal is to add an environment variable that will override the default port field on page load.

**Comment by dsgnr** [comment]
[@Zerof](https://github.com/ZEROF), I have a working branch in https://github.com/dsgnr/portchecker.io/tree/default_port_env_var which will allow the user to override the default port using an environment variable.

Testing with `docker run -it --name default_port_change  -e DEFAULT_PORT=443 -p 8080:8080 default_port_test` allows the default port to be modified on page load;
![image](https://user-images.githubusercontent.com/10280499/145541090-ced0561f-37b4-49fa-8d4c-bdf860bead99.png)

Please let me know if this is the kind of thing you were looking for, and I'll raise a PR to get this merged in.

**Comment by ZEROF** [comment]
Hi,

That's great. And yes, it's working well. thanks for integration.

**Comment by ZEROF** [comment]
Hi,

Port setting with ENV is not working. I pulled your image, i tried to build my own, but same results. 

```
docker-compose up -d
Pulling portchecker (dsgnr/portcheckerio-ui:latest)...
latest: Pulling from dsgnr/portcheckerio-ui
97518928ae5f: Already exists
a15dfa83ed30: Already exists
acae0b19bbc1: Already exists
fd4282442678: Already exists
b521ea0d9e3f: Already exists
b3282d03aa58: Already exists
8ec26ce6f3da: Pull complete
643e815a17f2: Pull complete
Digest: sha256:9eaada8bdef45c5f36c47f1cd932ce644fa1d6cbe482d60a8b77ac1147905457
Status: Downloaded newer image for dsgnr/portcheckerio-ui:latest
Creating portcheckerio ... done
```
Docker inspect showing this:

![image](https://user-images.githubusercontent.com/2687905/145695058-de5c1c84-4160-48ed-aaa4-485c4e7f148c.png)

It's empty:
![image](https://user-images.githubusercontent.com/2687905/145695071-44803918-c4be-4fd5-a121-b5c9e35840d3.png)

**Comment by dsgnr** [comment]
@ZEROF, since the Docker build compiles the files so they are static, simply modifying the env of the image after the fact won't make any changes to the UI.

Check out the instruction on how to add the PR https://github.com/dsgnr/portchecker.io/pull/8 explaining how to modify the port.
